---
title: "negmot"
output: html_document
---

# Preliminaries

```{r}
library(tidyverse)
library(here)
library(langcog)
```

```{r}
d_raw <- read_csv(here("data/Negation_May 1, 2019_02.18.csv"))
```

Data cleaning.

Note that for pilot, `bei` = touch it, `sha` = stay away.

```{r}
d <- d_raw %>%
  slice(-1:-2) %>%
  rename(id = ResponseId, 
         status = Status, 
         proh_bei = `Q5 Proh-bei`, 
         proh_sha = `Proh-sha`,
         nonexist_sha = `nonexit-sha`, 
         nonexist_bei = `nonexist-bei`, 
         condition = FL_13_DO) %>%
  select(id, status, starts_with("proh"), starts_with("nonex"), condition) %>%
  filter(status == "IP Address") %>%
  mutate(condition = case_when(condition == "TrainingC" ~ "congruent",
                               condition == "TrainingI" ~ "incongruent",
                               condition == "Training_no_cue" ~ "neutral"), 
         condition = fct_relevel(condition, "congruent", "neutral")) %>%
  gather(trial, response, starts_with("proh"), starts_with("nonexist")) %>%
  separate(trial, into=c("trial_type","word")) %>%
  mutate(trial_type = case_when(trial_type == "proh" ~ "prohibition",
                                trial_type == "nonexist" ~ "nonexistence"),
         correct = case_when(trial_type == "prohibition" & 
                               word == "bei" & response == "Touch it" ~ 1, 
                             trial_type == "prohibition" & 
                               word == "sha" & response == "Stay away" ~ 1, 
                             trial_type == "nonexistence" & 
                               word == "bei" & response == "Bucket" ~ 1, 
                             trial_type == "nonexistence" & 
                               word == "sha" & response == "Truck" ~ 1,
                             TRUE ~ 0))
```

# Analysis

Graph!

```{r}
ms <- d %>%
  group_by(condition, trial_type, word) %>% 
  multi_boot_standard(col = "correct")
```


```{r}
ggplot(ms, 
       aes(x = condition, y = mean, col = word)) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1)) + 
  facet_wrap(~trial_type) + 
  geom_hline(yintercept = .5, lty = 2) + 
  ylim(0,1)
```







